import { pgTable, serial, timestamp, integer, varchar, real, smallint, index } from 'drizzle-orm/pg-core';

export const machineSnapshots = pgTable('machine_snapshots', {
  id: serial('id').primaryKey(),
  timestamp: timestamp('timestamp', { withTimezone: true }).notNull().defaultNow(),

  // INT fields (S1_I_DATO_1 through S1_I_DATO_72) — 16-bit signed
  thermoLeftLower: integer('thermo_left_lower'),
  thermoLeftMedium: integer('thermo_left_medium'),
  thermoLeftUpper: integer('thermo_left_upper'),
  thermoRightLower: integer('thermo_right_lower'),
  thermoRightMedium: integer('thermo_right_medium'),
  thermoRightUpper: integer('thermo_right_upper'),
  thermoLeftHighLower: integer('thermo_left_high_lower'),
  thermoLeftHighMedium: integer('thermo_left_high_medium'),
  thermoLeftHighUpper: integer('thermo_left_high_upper'),
  thermoRightHighLower: integer('thermo_right_high_lower'),
  garbageTemp: integer('garbage_temp'),
  holdingTempSetpoint: integer('holding_temp_setpoint'),
  chamberPressure: integer('chamber_pressure'),
  mainMotorSpeed: integer('main_motor_speed'),
  mainMotorTorque: integer('main_motor_torque'),
  mainMotorCurrent: integer('main_motor_current'),
  vacuumPumpSpeed01: integer('vacuum_pump_speed_01'),
  vacuumPumpSpeed02: integer('vacuum_pump_speed_02'),
  spareInt19: integer('spare_int_19'),
  spareInt20: integer('spare_int_20'),
  spareInt21: integer('spare_int_21'),
  spareInt22: integer('spare_int_22'),
  spareInt23: integer('spare_int_23'),
  spareInt24: integer('spare_int_24'),
  spareInt25: integer('spare_int_25'),
  spareInt26: integer('spare_int_26'),
  spareInt27: integer('spare_int_27'),
  spareInt28: integer('spare_int_28'),
  spareInt29: integer('spare_int_29'),
  spareInt30: integer('spare_int_30'),
  spareInt31: integer('spare_int_31'),
  spareInt32: integer('spare_int_32'),
  spareInt33: integer('spare_int_33'),
  spareInt34: integer('spare_int_34'),
  spareInt35: integer('spare_int_35'),
  spareInt36: integer('spare_int_36'),
  spareInt37: integer('spare_int_37'),
  spareInt38: integer('spare_int_38'),
  spareInt39: integer('spare_int_39'),
  spareInt40: integer('spare_int_40'),
  spareInt41: integer('spare_int_41'),
  spareInt42: integer('spare_int_42'),
  spareInt43: integer('spare_int_43'),
  spareInt44: integer('spare_int_44'),
  spareInt45: integer('spare_int_45'),
  spareInt46: integer('spare_int_46'),
  spareInt47: integer('spare_int_47'),
  spareInt48: integer('spare_int_48'),
  spareInt49: integer('spare_int_49'),
  spareInt50: integer('spare_int_50'),
  spareInt51: integer('spare_int_51'),
  spareInt52: integer('spare_int_52'),
  spareInt53: integer('spare_int_53'),
  spareInt54: integer('spare_int_54'),
  spareInt55: integer('spare_int_55'),
  spareInt56: integer('spare_int_56'),
  materialInputWeight: integer('material_input_weight'),
  materialOutputWeight: integer('material_output_weight'),
  selectedCycle: integer('selected_cycle'),
  currentPhase: integer('current_phase'),
  machineStatus: integer('machine_status'),
  spareInt62: integer('spare_int_62'),
  spareInt63: integer('spare_int_63'),
  spareInt64: integer('spare_int_64'),
  spareInt65: integer('spare_int_65'),
  spareInt66: integer('spare_int_66'),
  spareInt67: integer('spare_int_67'),
  spareInt68: integer('spare_int_68'),
  spareInt69: integer('spare_int_69'),
  spareInt70: integer('spare_int_70'),
  spareInt71: integer('spare_int_71'),
  spareInt72: integer('spare_int_72'),

  // DINT fields (S1_DI_DATO_1, S1_DI_DATO_2) — 32-bit signed
  completedCycles: integer('completed_cycles'),
  spareDint01: integer('spare_dint_01'),

  // STRING[20] fields (S1_S_DATO_1 through S1_S_DATO_5)
  user: varchar('user', { length: 20 }),
  supervisor: varchar('supervisor', { length: 20 }),
  orderNumber: varchar('order_number', { length: 20 }),
  serialNumber: varchar('serial_number', { length: 20 }),
  spareString01: varchar('spare_string_01', { length: 20 }),

  // REAL fields (S1_R_DATO_1 through S1_R_DATO_7) — 32-bit float
  energyConsumption: real('energy_consumption'),
  rmsCurrL1: real('rms_curr_l1'),
  rmsCurrL2: real('rms_curr_l2'),
  rmsCurrL3: real('rms_curr_l3'),
  rmsCurrN: real('rms_curr_n'),
  waterConsumption: real('water_consumption'),
  spareReal01: real('spare_real_01'),

  // BYTE fields (S1_B_DATO_1 through S1_B_DATO_6) — 8-bit unsigned
  thermoLeftLowSel: smallint('thermo_left_low_sel'),
  thermoLeftMedSel: smallint('thermo_left_med_sel'),
  thermoLeftHighSel: smallint('thermo_left_high_sel'),
  thermoRightLowSel: smallint('thermo_right_low_sel'),
  thermoRightMedSel: smallint('thermo_right_med_sel'),
  thermoRightHighSel: smallint('thermo_right_high_sel'),
}, (table) => [
  index('machine_snapshots_timestamp_idx').on(table.timestamp),
]);
