#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# WPT IoT - Linux Install Script (dev / staging VM)
# =============================================================================
# One-shot, idempotent installer for Linux hosts that need the real PLC UDP
# path plus the HTTPS/PWA frontend surface.
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
ok()    { echo -e "${GREEN}[ OK ]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }
step()  { echo ""; echo -e "${CYAN}========== $1 ==========${NC}"; }

upsert_env() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}=" .env; then
    sed -i "s|^${key}=.*|${key}=${value}|" .env
  else
    echo "${key}=${value}" >> .env
  fi
}

[[ "$(uname -s)" == "Linux" ]] || fail "This script targets Linux only."
[[ $EUID -ne 0 ]] || fail "Do not run as root. Run as your normal user."
command -v docker >/dev/null 2>&1 || fail "Docker not installed."
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 not available."
command -v openssl >/dev/null 2>&1 || fail "openssl not installed."
[[ -f docker-compose.yml ]] || fail "docker-compose.yml not found in $PROJECT_DIR."
[[ -f docker-compose.https.yml ]] || fail "docker-compose.https.yml not found."

LAN_IP="$(hostname -I | awk '{print $1}')"
[[ -n "$LAN_IP" ]] || fail "Could not detect LAN IP via 'hostname -I'."

step "WPT IoT Linux Installer"
info "Project dir: $PROJECT_DIR"
info "Detected LAN IP: $LAN_IP"
info "Frontend URL: https://wpt.local"
info "API URL: https://wpt.local/api"
info "Backend UDP path: host networking"

step "Step 1/9  Stop conflicting host services"

if systemctl is-active --quiet grafana-server 2>/dev/null; then
  warn "Found grafana-server bound on :3000 - stopping it."
  sudo systemctl stop grafana-server
  sudo systemctl disable grafana-server 2>/dev/null || true
  sudo apt purge -y grafana 2>/dev/null || sudo apt purge -y grafana-server 2>/dev/null || true
  ok "grafana-server removed."
else
  ok "Port 3000 not held by grafana."
fi

if snap list mosquitto >/dev/null 2>&1; then
  warn "Found snap mosquitto - removing it."
  sudo snap remove --purge mosquitto
  ok "snap mosquitto removed."
elif systemctl is-active --quiet mosquitto 2>/dev/null; then
  warn "Found systemd mosquitto - stopping it."
  sudo systemctl stop mosquitto
  sudo systemctl disable mosquitto 2>/dev/null || true
  ok "systemd mosquitto stopped."
else
  ok "Port 1883 not held by host mosquitto."
fi

step "Step 2/9  Install avahi-daemon and publish mDNS aliases"

if ! command -v avahi-publish >/dev/null 2>&1; then
  warn "avahi-utils not installed - installing."
  sudo apt-get update -qq
  sudo apt-get install -y -qq avahi-daemon avahi-utils libnss-mdns >/dev/null
  ok "avahi-daemon + avahi-utils + libnss-mdns installed."
else
  ok "avahi-utils already present."
fi

if ! systemctl is-active --quiet avahi-daemon; then
  sudo systemctl enable --now avahi-daemon
fi
ok "avahi-daemon active."

sudo install -m 0755 "${SCRIPT_DIR}/wpt-local-alias.sh" /usr/local/sbin/wpt-local-alias.sh

sudo tee /etc/systemd/system/wpt-local-alias.service > /dev/null << 'UNITEOF'
[Unit]
Description=Publish wpt.local mDNS alias for WPT IoT
After=avahi-daemon.service network-online.target
Requires=avahi-daemon.service
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/sbin/wpt-local-alias.sh
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNITEOF

sudo systemctl daemon-reload
sudo systemctl enable wpt-local-alias.service >/dev/null 2>&1
sudo systemctl restart wpt-local-alias.service
sleep 2

if avahi-resolve-host-name wpt.local >/dev/null 2>&1; then
  ok "wpt.local resolves on the local machine."
else
  warn "wpt.local did not resolve immediately. mDNS may need a few seconds."
fi

step "Step 3/9  Configure .env"

if [[ ! -f .env ]]; then
  [[ -f .env.example ]] || fail "No .env and no .env.example to copy from."
  cp .env.example .env
  info "Created .env from .env.example."
else
  info ".env already exists - updating HTTPS-specific values only."
fi

upsert_env "CORS_ORIGIN" "https://wpt.local"
upsert_env "NEXT_PUBLIC_API_URL" "https://wpt.local/api"
upsert_env "SESSION_COOKIE_SECURE" "true"
upsert_env "TRUST_PROXY" "true"
ok ".env updated for HTTPS + secure cookies."

step "Step 4/9  Generate docker-compose.host.yml"

cat > docker-compose.host.yml << EOF
# Auto-generated by scripts/install-linux.sh - do not edit by hand.

services:
  backend:
    network_mode: host
    ports: !override []
    environment:
      MQTT_HOST: 127.0.0.1
      PG_HOST: 127.0.0.1
      CORS_ORIGIN: https://wpt.local
      SESSION_COOKIE_SECURE: "true"
      TRUST_PROXY: "true"

  frontend:
    build:
      args:
        NEXT_PUBLIC_API_URL: https://wpt.local/api
    environment:
      NEXT_PUBLIC_API_URL: https://wpt.local/api
EOF
ok "docker-compose.host.yml written."

step "Step 5/9  Generate local TLS certificates"

mkdir -p certs
bash scripts/generate-local-tls.sh certs "${LAN_IP}"
ok "TLS assets ready in ${PROJECT_DIR}/certs."

step "Step 6/9  Ensure user is in docker group"

if id -nG "$USER" | grep -qw docker; then
  ok "$USER is already in the docker group."
  DOCKER="docker"
else
  warn "Adding $USER to docker group (sudo)."
  sudo usermod -aG docker "$USER"
  warn "You must log out and back in for docker group membership to apply in new sessions."
  DOCKER="sudo docker"
fi

COMPOSE_FILES=(-f docker-compose.yml -f docker-compose.host.yml -f docker-compose.https.yml)

step "Step 7/9  Start db + mosquitto"

$DOCKER compose "${COMPOSE_FILES[@]}" up -d db mosquitto

info "Waiting for db to become healthy..."
for i in {1..30}; do
  if $DOCKER compose "${COMPOSE_FILES[@]}" ps db --format json 2>/dev/null | grep -q '"Health":"healthy"'; then
    ok "db is healthy."
    break
  fi
  sleep 2
  [[ $i -eq 30 ]] && fail "db failed to become healthy in 60s."
done

step "Step 8/9  Migrate schema"

info "Running migration in a throwaway node:22-alpine container..."
$DOCKER run --rm \
  --network host \
  -v "$PROJECT_DIR:/src:ro" \
  -e PG_HOST=127.0.0.1 \
  -e PG_PORT=5432 \
  -e PG_DB=wpt \
  -e PG_USERNAME=wpt \
  -e PG_PASSWORD="${PG_PASSWORD:-wpt_dev_password}" \
  node:22-alpine \
  sh -c "set -e && apk add --no-cache rsync >/dev/null && rsync -a --exclude=node_modules --exclude='apps/*/node_modules' --exclude='packages/*/node_modules' --exclude=.git /src/ /app/ && cd /app && corepack enable && pnpm install --frozen-lockfile --filter @wpt/backend --filter @wpt/types >/dev/null 2>&1 && pnpm -r --filter @wpt/backend run db:push"
ok "Schema migration complete."

step "Step 9/9  Build and start backend + frontend + nginx"

$DOCKER compose "${COMPOSE_FILES[@]}" up -d --build backend frontend nginx

info "Waiting for backend /health..."
for i in {1..30}; do
  if curl -fsS -m 2 "http://127.0.0.1:3000/health" >/dev/null 2>&1; then
    ok "backend /health responds."
    break
  fi
  sleep 2
  [[ $i -eq 30 ]] && fail "backend /health did not respond in 60s."
done

info "Waiting for nginx health..."
for i in {1..30}; do
  if curl -fsS -m 2 "http://127.0.0.1/nginx-health" >/dev/null 2>&1; then
    ok "nginx /nginx-health responds."
    break
  fi
  sleep 2
  [[ $i -eq 30 ]] && fail "nginx /nginx-health did not respond in 60s."
done

info "Waiting for HTTPS frontend..."
for i in {1..30}; do
  if curl --silent --show-error --fail --cacert "${PROJECT_DIR}/certs/wpt-local-ca.crt" --resolve wpt.local:443:127.0.0.1 "https://wpt.local/" >/dev/null 2>&1; then
    ok "HTTPS frontend responds."
    break
  fi
  sleep 2
  [[ $i -eq 30 ]] && fail "HTTPS frontend did not respond in 60s."
done

echo ""
echo -e "${GREEN}=========================================="
echo "  WPT IoT installed and running"
echo -e "==========================================${NC}"
echo ""
echo "  Frontend:    https://wpt.local"
echo "  API:         https://wpt.local/api/health"
echo "  Local CA:    ${PROJECT_DIR}/certs/wpt-local-ca.crt"
echo "  Backend:     http://127.0.0.1:3000/health (maintenance only)"
echo ""
echo "Next steps:"
echo "  1. Trust ${PROJECT_DIR}/certs/wpt-local-ca.crt on the client devices that open the app."
echo "  2. Open https://wpt.local in a browser."
echo "  3. In CODESYS V2, set GVL_WPT.sTargetIp := '${LAN_IP}' so the PLC streams here."
echo ""
