#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# WPT IoT — Linux Install Script (dev / staging VM)
# =============================================================================
# One-shot, idempotent installer for any Linux host (Ubuntu/Debian tested).
# Different from setup-onlogic.sh: this script is for non-production VMs that
# need to talk to a real PLC. It uses host networking on the backend so PLC
# UDP frames reach the listener sockets directly, but builds images locally
# instead of pulling from GHCR (no auth required).
#
# Usage:
#   cd wpt-iot
#   bash scripts/install-linux.sh
#
# Re-running is safe — every step checks current state before acting.
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
ok()    { echo -e "${GREEN}[ OK ]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }
step()  { echo ""; echo -e "${CYAN}========== $1 ==========${NC}"; }

# --- Sanity checks ---
[[ "$(uname -s)" == "Linux" ]] || fail "This script targets Linux only. For Windows/Mac dev, use 'pnpm dev' instead."
[[ $EUID -ne 0 ]] || fail "Do NOT run as root. Run as your normal user — the script uses sudo where needed."
command -v docker >/dev/null 2>&1 || fail "Docker not installed. Install via: curl -fsSL https://get.docker.com | sh"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 plugin not available."
[[ -f docker-compose.yml ]] || fail "docker-compose.yml not found in $PROJECT_DIR. Run from inside the wpt-iot/ directory."

# Detect LAN IP (first non-loopback IPv4)
LAN_IP="$(hostname -I | awk '{print $1}')"
[[ -n "$LAN_IP" ]] || fail "Could not detect LAN IP via 'hostname -I'."

step "WPT IoT Linux Installer"
info "Project dir: $PROJECT_DIR"
info "Detected LAN IP: $LAN_IP"
info "Backend will bind: 0.0.0.0:3000 (host networking)"
info "Frontend bundle will point browser at: http://${LAN_IP}:3000"

# =============================================================================
# 1. Free conflicting ports (legacy host services)
# =============================================================================
step "Step 1/7  Stop conflicting host services"

if systemctl is-active --quiet grafana-server 2>/dev/null; then
  warn "Found grafana-server bound on :3000 — purging (frees backend port)."
  sudo systemctl stop grafana-server
  sudo systemctl disable grafana-server 2>/dev/null || true
  sudo apt purge -y grafana 2>/dev/null || sudo apt purge -y grafana-server 2>/dev/null || true
  ok "grafana-server removed."
else
  ok "Port 3000 not held by grafana."
fi

if snap list mosquitto >/dev/null 2>&1; then
  warn "Found snap mosquitto — removing (containerised mosquitto will replace it)."
  sudo snap remove --purge mosquitto
  ok "snap mosquitto removed."
elif systemctl is-active --quiet mosquitto 2>/dev/null; then
  warn "Found systemd mosquitto — stopping (does NOT uninstall)."
  sudo systemctl stop mosquitto
  sudo systemctl disable mosquitto 2>/dev/null || true
  ok "systemd mosquitto stopped."
else
  ok "Port 1883 not held by host mosquitto."
fi

# Note: we don't pre-check ports because Docker itself will fail loudly if a
# real conflict remains, and the explicit grafana/mosquitto checks above
# already handle the only known host services that grab our ports.
ok "Conflicting host services handled."

# =============================================================================
# 2. .env file
# =============================================================================
step "Step 2/7  Configure .env"

if [[ ! -f .env ]]; then
  if [[ -f .env.example ]]; then
    cp .env.example .env
    info "Created .env from .env.example."
  else
    fail "No .env and no .env.example to copy from."
  fi
else
  info ".env already exists — updating LAN-specific values only."
fi

# CORS_ORIGIN must include the LAN frontend URL AND wpt.local so browsers can
# reach the API from either the raw IP or the mDNS hostname (set up later).
sed -i "s|^CORS_ORIGIN=.*|CORS_ORIGIN=http://wpt.local:3001,http://${LAN_IP}:3001,http://localhost:3001|" .env
sed -i "s|^NEXT_PUBLIC_API_URL=.*|NEXT_PUBLIC_API_URL=http://${LAN_IP}:3000|" .env
ok "CORS_ORIGIN and NEXT_PUBLIC_API_URL set to LAN IP $LAN_IP + wpt.local."

# =============================================================================
# 3. Host networking override
# =============================================================================
step "Step 3/7  Generate docker-compose.host.yml"

cat > docker-compose.host.yml << EOF
# Auto-generated by scripts/install-linux.sh — DO NOT EDIT BY HAND.
# Re-run install-linux.sh to regenerate with the current LAN IP.
#
# This override puts the backend on host networking so the real PLC's UDP
# frames reach the listener sockets directly (Docker bridge port mapping
# silently drops PLC UDP on Windows/Mac and is unreliable on Linux for
# multi-NIC hosts). Frontend stays on bridge networking; its bundled
# NEXT_PUBLIC_API_URL is overridden so the browser fetches from the LAN URL.

services:
  backend:
    network_mode: host
    ports: !override []
    environment:
      MQTT_HOST: 127.0.0.1
      PG_HOST: 127.0.0.1
      CORS_ORIGIN: http://${LAN_IP}:3001,http://wpt.local:3001,http://localhost:3001

  frontend:
    # Bake the frontend bundle to call the API at the raw LAN IP. Earlier
    # versions baked http://wpt.local:3000 to keep the cookie SameSite=Lax
    # path clean, but that strategy is fragile in the field: any stale
    # mDNS cache (router DNS, Windows DNS Client, another VM still
    # advertising the old IP) silently routes the browser at the wrong
    # host and the auth POST surfaces as ERR_CONNECTION_REFUSED with no
    # signal that wpt.local is the culprit. Raw IP always reaches THIS
    # host. SameSite=Lax is fine because the page itself is also served
    # from the same raw-IP origin (frontend on http://${LAN_IP}:3001),
    # so the cookie stays first-party.
    build:
      args:
        NEXT_PUBLIC_API_URL: http://${LAN_IP}:3000
    environment:
      NEXT_PUBLIC_API_URL: http://${LAN_IP}:3000
EOF
ok "docker-compose.host.yml written."

# =============================================================================
# 4. Docker group membership (so future runs don't need sudo)
# =============================================================================
step "Step 4/7  Ensure user is in docker group"

if id -nG "$USER" | grep -qw docker; then
  ok "$USER is already in the docker group."
else
  warn "Adding $USER to docker group (sudo)."
  sudo usermod -aG docker "$USER"
  warn "You must log out and back in for docker group to take effect in NEW sessions."
  warn "For THIS run we will continue using sudo for docker commands."
  DOCKER="sudo docker"
fi
DOCKER="${DOCKER:-docker}"

# =============================================================================
# 5. Bring up db + mosquitto first, wait healthy, then run migration
# =============================================================================
step "Step 5/7  Start db + mosquitto"

COMPOSE_FILES=(-f docker-compose.yml -f docker-compose.host.yml)
$DOCKER compose "${COMPOSE_FILES[@]}" up -d db mosquitto

info "Waiting for db to become healthy..."
for i in {1..30}; do
  if $DOCKER compose "${COMPOSE_FILES[@]}" ps db --format json 2>/dev/null | grep -q '"Health":"healthy"'; then
    ok "db is healthy."
    break
  fi
  sleep 2
  [[ $i -eq 30 ]] && fail "db failed to become healthy in 60s."
done

# =============================================================================
# 6. Run drizzle db:push via one-shot Node container (no host pnpm needed)
# =============================================================================
step "Step 6/7  Migrate database schema (drizzle-kit push)"

info "Running migration in throwaway node:22-alpine container..."
$DOCKER run --rm \
  --network host \
  -v "$PROJECT_DIR:/src:ro" \
  -e PG_HOST=127.0.0.1 \
  -e PG_PORT=5432 \
  -e PG_DB=wpt \
  -e PG_USERNAME=wpt \
  -e PG_PASSWORD="${PG_PASSWORD:-wpt_dev_password}" \
  node:22-alpine \
  sh -c "set -e && apk add --no-cache rsync >/dev/null && rsync -a --exclude=node_modules --exclude='apps/*/node_modules' --exclude='packages/*/node_modules' --exclude=.git /src/ /app/ && cd /app && corepack enable && pnpm install --frozen-lockfile --filter @wpt/backend --filter @wpt/types >/dev/null 2>&1 && pnpm -r --filter @wpt/backend run db:push"

ok "Schema migration complete."

# =============================================================================
# 7. Bring up backend + frontend (build if needed)
# =============================================================================
step "Step 7/7  Build and start backend + frontend"

$DOCKER compose "${COMPOSE_FILES[@]}" up -d --build backend frontend

info "Waiting for backend health..."
for i in {1..30}; do
  if curl -fsS -m 2 "http://127.0.0.1:3000/health" >/dev/null 2>&1; then
    ok "backend /health responds."
    break
  fi
  sleep 2
  [[ $i -eq 30 ]] && fail "backend /health did not respond in 60s. Check: $DOCKER logs wpt-iot-backend-1"
done

info "Waiting for frontend..."
for i in {1..30}; do
  if curl -fsS -m 2 -o /dev/null "http://127.0.0.1:3001/" 2>/dev/null; then
    ok "frontend / responds."
    break
  fi
  sleep 2
  [[ $i -eq 30 ]] && warn "frontend / did not respond in 60s — check: $DOCKER logs wpt-iot-frontend-1"
done

# =============================================================================
# Done
# =============================================================================
echo ""
echo -e "${GREEN}=========================================="
echo "  WPT IoT installed and running"
echo -e "==========================================${NC}"
echo ""
echo "  Frontend:    http://${LAN_IP}:3001"
echo "  Backend:     http://${LAN_IP}:3000/health"
echo "  DB:          127.0.0.1:5432 (user wpt)"
echo "  MQTT broker: 127.0.0.1:1883"
echo ""
echo "Next steps:"
echo "  1. In CODESYS V2, set GVL_WPT.sTargetIp := '${LAN_IP}' so the PLC streams here."
echo "  2. Set xStreamData := TRUE and xStreamAlarms := TRUE."
echo "  3. Watch packets land:"
echo "       curl -s http://${LAN_IP}:3000/health | jq"
echo ""
